server:
  port: 80


spring:
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  # thymeleaf模板设置
  thymeleaf:
    cache: false
    mode: HTML
    check-template: true
    servlet:
      content-type: text/html
    encoding: utf-8
    prefix: classpath:/static/
    suffix: .html
    enabled: true
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
  #配置数据源
  datasource:
    url: jdbc:mysql://119.29.14.89:3306/restaurant?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      aop-patterns: ltd.linqiu.*
      filters: stat,wall,slf4j
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      filter:
        stat: # sql监控
          enabled: true
          slow-sql-millis: 1000
          log-slow-sql: true
        wall: # 防火墙
          enabled: true
          config:
            drop-table-allow: false



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: ltd.linqiu.entity
  configuration:
    map-underscore-to-camel-case: true # 匹配驼峰命名

